TaskType = "Search"

[SearchParameters]
DisposeOfFileWhenDone = true
DoParsimony = true
ModPeptidesAreDifferent = false
NoOneHitWonders = false
MatchBetweenRuns = false
Normalize = false
QuantifyPpmTol = 5.0
DoHistogramAnalysis = true
SearchTarget = true
DecoyType = "Reverse"
MassDiffAcceptorType = "Exact"
WritePrunedDatabase = true
KeepAllUniprotMods = true
DoLocalizationAnalysis = false
DoQuantification = false
DoMbrAnalysis = true
SearchType = "Modern"
LocalFdrCategories = ["FullySpecific"]
MaxFragmentSize = 30000.0
MinAllowedInternalFragmentLength = 10
HistogramBinTolInDaltons = 0.003
MaximumMassThatFragmentIonScoreIsDoubled = 0.0
WriteMzId = true
WritePepXml = false
WriteDecoys = true
WriteContaminants = true
WriteIndividualFiles = true
WriteSpectralLibrary = false
UpdateSpectralLibrary = false
CompressIndividualFiles = false
TCAmbiguity = "RemoveContaminant"
IncludeModMotifInMzid = false

[SearchParameters.ModsToWriteSelection]
'Common Fixed' = 3
'Common Variable' = 3
'N-linked glycosylation' = 3
'O-linked glycosylation' = 3
'Other glycosylation' = 3
'Common Biological' = 3
'Less Common' = 3
'Common Artifact' = 3
Metal = 3
Speculative = 3
'AspN Digested' = 3
'Trypsin Digested' = 3
Protease = 3
'2+ nucleotide substitution' = 3
'1 nucleotide substitution' = 3
Surfactant = 3
'Multiplex Label' = 3
UniProt = 3
Unimod = 3

[CommonParameters]
TaskDescriptor = "SearchTask"
MaxThreadsToUsePerFile = 19
ListOfModsFixed = ""
ListOfModsVariable = "Common Variable\tOxidation on M"
DoPrecursorDeconvolution = true
UseProvidedPrecursorInfo = false
DeconvolutionIntensityRatio = 3.0
DeconvolutionMaxAssumedChargeState = 80
DeconvolutionMassTolerance = "±4.0000 PPM"
TotalPartitions = 20
ProductMassTolerance = "±10.0000 PPM"
PrecursorMassTolerance = "±10.0000 PPM"
AddCompIons = true
ScoreCutoff = 5.0
ReportAllAmbiguity = true
NumberOfPeaksToKeepPerWindow = 200
MinimumAllowedIntensityRatioToBasePeak = 0.01
NormalizePeaksAccrossAllWindows = false
TrimMs1Peaks = false
TrimMsMsPeaks = false
UseDeltaScore = false
QValueOutputFilter = 1.0
PepQValueOutputFilter = 1.0
CustomIons = []
AssumeOrphanPeaksAreZ1Fragments = false
MaxHeterozygousVariants = 4
MinVariantDepth = 1
AddTruncations = false
DissociationType = "HCD"
SeparationType = "HPLC"
MS2ChildScanDissociationType = "Unknown"
MS3ChildScanDissociationType = "Unknown"

[CommonParameters.DigestionParams]
MaxMissedCleavages = 2
InitiatorMethionineBehavior = "Variable"
MinPeptideLength = 7
MaxPeptideLength = 2147483647
MaxModificationIsoforms = 1024
MaxModsForPeptide = 2
Protease = "top-down"
SearchModeType = "Full"
FragmentationTerminus = "Both"
SpecificProtease = "top-down"
GeneratehUnlabeledProteinsForSilac = true
KeepNGlycopeptide = false
KeepOGlycopeptide = false

[[FileSpecificParameters]]
[[FileSpecificParameters]]
[[FileSpecificParameters]]
[[FileSpecificParameters]]
